### ISSUE TITLE
key must be 32 bytes

### ISSUE THREAD

**Issue by phil** [heroku/heroku-bouncer#57]
Currently upgrading to Ruby 2.4.2 is breaking bouncer.

**Comment by phil** [comment]
```
ArgumentError - key must be 32 bytes:
  heroku-bouncer (0.8.0) lib/heroku/bouncer/lockbox.rb:11:in `lock'
  heroku-bouncer (0.8.0) lib/heroku/bouncer/decrypted_hash.rb:35:in `lock'
  heroku-bouncer (0.8.0) lib/heroku/bouncer/middleware.rb:222:in `encrypt_store'
  heroku-bouncer (0.8.0) lib/heroku/bouncer/middleware.rb:154:in `unlock_session_data'
  heroku-bouncer (0.8.0) lib/heroku/bouncer/middleware.rb:57:in `call'
```

**Comment by wuputah** [comment]
Currently we truncate keys to 32 chars. The new version of OpenSSL in Ruby 2.4.2 seems to be _requiring_ a 32 character key. Users will need to pass a key of at least 32 characters to workaround this error.
