### ISSUE TITLE
NameError (undefined local variable or method `local_variables' for #<Heroku::Bouncer::Lockbox:0x007f83075d9af8>):

### ISSUE THREAD

**Issue by phil** [heroku/heroku-bouncer#58]
```
NameError (undefined local variable or method `local_variables' for #<Heroku::Bouncer::Lockbox:0x007f83075d9af8>):
  heroku-bouncer (0.8.0) lib/heroku/bouncer/lockbox.rb:11:in `lock'
  better_errors (2.1.1) lib/better_errors/stack_frame.rb:71:in `eval'
  better_errors (2.1.1) lib/better_errors/stack_frame.rb:71:in `local_variables'
```

**Comment by wuputah** [comment]
The gem does not use `local_variables`. Stop using `better_errors`, perhaps?
